"""empty message

Revision ID: 075a1b4493d4
Revises: 8ada4e0908e0
Create Date: 2018-08-09 17:45:13.110544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '075a1b4493d4'
down_revision = '8ada4e0908e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reminder')
    # ### end Alembic commands ###
