"""empty message

Revision ID: 37b4495458e6
Revises: 994b84c41f15
Create Date: 2018-08-07 11:58:23.414982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37b4495458e6'
down_revision = '994b84c41f15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'description')
    # ### end Alembic commands ###
