"""empty message

Revision ID: 856cc0f5411f
Revises: 37b4495458e6
Create Date: 2018-08-07 18:23:53.783039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '856cc0f5411f'
down_revision = '37b4495458e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('is_delete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'is_delete')
    # ### end Alembic commands ###
